### ISSUE TITLE
ragarding path folder for bsd image dataset

### ISSUE THREAD

**Issue by pandagre** [randy3k/AutomaticPackageReloader#34]
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:/Users/basant/PycharmProjects/CNN-Image-Denoising/CNN_Image_Denoising.py", line 36, in <module>
    grayscale_resize_images(path_train_img, fraction)
  File "C:/Users/basant/PycharmProjects/CNN-Image-Denoising/CNN_Image_Denoising.py", line 29, in grayscale_resize_images
    for filename in os.listdir(path_images):
FileNotFoundError: [WinError 3] The system cannot find the path specified: '.\\BSR\\train'

**Comment by randy3k** [comment]
How is it related to this package?
