### ISSUE TITLE
Sublime Text 3 Compatibility Issue

### ISSUE THREAD

**Issue by deathaxe** [randy3k/AutomaticPackageReloader#48]
Running the plugin on Sublime Text 3 causes...

```
Exception in thread AutomaticPackageReloader:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "Sublime Text 3176\Data\Packages\AutomaticPackageReloader\package_reloader.py", line 117, in run_async
    package, dependencies=dependencies, extra_modules=extra_modules, verbose=verbose)
  File "Sublime Text 3176\Data\Packages\AutomaticPackageReloader\reloader\reloader.py", line 110, in reload_package
    sublime_plugin.load_module(module)
AttributeError: 'module' object has no attribute 'load_module'
```

**Comment by mkruselj** [comment]
I get this:

```
Exception in thread AutomaticPackageReloader:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "C:\Program Files\Sublime Text\Data\Packages\AutomaticPackageReloader\package_reloader.py", line 117, in run_async
    package, dependencies=dependencies, extra_modules=extra_modules, verbose=verbose)
  File "C:\Program Files\Sublime Text\Data\Packages\AutomaticPackageReloader\reloader\reloader.py", line 80, in reload_package
    for parent in resolve_parents(package):
  File "C:\Program Files\Sublime Text\Data\Packages\AutomaticPackageReloader\reloader\resolver.py", line 14, in resolve_parents
    everything = manager.list_packages() + manager.list_dependencies()
AttributeError: 'PackageManager' object has no attribute 'list_dependencies'
```

**Comment by deathaxe** [comment]
That's another issue unrelated with ST3.

It is addressed by https://github.com/randy3k/AutomaticPackageReloader/pull/42.

**Comment by mkruselj** [comment]
Cool good to know. I have all issues fixed by manually applying all open PRs. Would be nice if they'd be merged and updaste to APR officially pushed :)

**Comment by deathaxe** [comment]
Fixed by https://github.com/randy3k/AutomaticPackageReloader/commit/3b1ba2a890869f14196a09c55c2127dee783f8e2

Also noted, PC installs 1.3.8 on ST3, which is not affected.
